language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc


addons:
  apt:
    packages:
# only have check 0.9 on trusty.
#    - check
# Only have libusb-dev 0.1.. we want 0.9.1+
#    - libusb-dev
    - libavahi-client-dev
    - swig

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install php; fi

before_script:
  - ./bootstrap

script:
  - ./configure && make -j 2
# libcheck no present
#  - make check
